M48
; DRILL file {KiCad 9.0.3} date 2026-09-07T16:07:47+0200
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-07T16:07:47+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.3
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.600
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.500
%
G90
G05
T1
X95.3Y-109.0
T2
X102.6Y-63.0
X137.4Y-109.8
M30
